name: Survey Marketplace Install, Test and Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.17.0]
    
    env:
      MNEMONICS: ${{ secrets.MNEMONICS}}
      INFURA_KEY: ${{ secrets.INFURA_KEY}}

    steps:
      - name: Checkout Use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2
      
      - name: Install
        run: |
          cd ./survey-marketplace-truffle && yarn
      - name: Test
        run: |
          cd ./survey-marketplace-truffle && yarn test
      - name: Ropsten deploy 
        if: github.ref == 'refs/heads/master'
        run: |
          cd ./survey-marketplace-truffle && yarn ropsten-deploy
          
