name: Survey Marketplace Install, Test and Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.17.0]

    steps:
      - name: Checkout Use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2
      
      - name: Install
        run: |
          cd ./survey-marketplace-truffle && yarn
      - name: Test
        run: |
          cd ./survey-marketplace-truffle && yarn test
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
          node-version: [10.17.0]
    
    env:
      MNEMONIC: ${{ secrets.MNEMONICS}}
      INFURA_ID: ${{ secrets.INFURA_KEY}}
    
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2
        with:
          persist-credential: false
      
      - name: Ropsten Deploy
        run: |
          cd ./survey-marketplace-truffle && yarn
          yarn ropsten-deploy